on:
  workflow_call:

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - run: npm ci

      - name: Compile the TypeScript files
        run: npx tsc

      - name: Test
        run: npm test
